version: '3.8'

services:
  # DORA Metrics Microservice
  dora-api:
    build: 
      context: ./microservice
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
    env_file:
      - ./microservice/.env
    volumes:
      - ./microservice:/app
      - /app/node_modules
    networks:
      - dora-network

  # DORA Metrics Frontend
  dora-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - VITE_API_BASE_URL=http://localhost:3001/api/v1/dora
    env_file:
      - ./frontend/.env.local
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - dora-api
    networks:
      - dora-network

networks:
  dora-network:
    driver: bridge